---
id: jonah
name: Jonah
full: Newsfeed application
description: |
  Jonah is a portal system for displaying news and other data
  from various sources, written in PHP and utilizing the Horde Application
  Framework.
list: horde
type: application
